import AppKit

// MARK: - Polls/observes the system pasteboard for new clipboard content

/// Polls `NSPasteboard.general.changeCount` on a timer and turns new
/// content into persisted `ClipboardItem`s. If the new content's hash
/// matches the most recent item, no duplicate is created — that item's
/// `lastUsedAt` is refreshed instead.
final class ClipboardMonitor {
    static let pollInterval: TimeInterval = 0.3

    /// Called after a new item has been created and persisted.
    var onNewItem: ((ClipboardItem) -> Void)?
    /// Called after an existing item's `lastUsedAt` has been refreshed.
    var onUpdateItem: ((ClipboardItem) -> Void)?

    private static let lock = NSLock()
    private static var ignoredChangeCounts = Set<Int>()
    private static weak var activeMonitor: ClipboardMonitor?

    private var timer: Timer?
    private var lastChangeCount: Int

    init() {
        lastChangeCount = NSPasteboard.general.changeCount
        Self.lock.lock()
        Self.activeMonitor = self
        Self.lock.unlock()
    }

    /// Records a change count generated by Clippy itself so it is never ingested.
    static func recordOwnWrite(changeCount: Int) {
        lock.lock()
        defer { lock.unlock() }
        ignoredChangeCounts.insert(changeCount)
        activeMonitor?.lastChangeCount = changeCount
    }

    deinit {
        stop()
    }

    func start() {
        stop()
        let timer = Timer(timeInterval: Self.pollInterval, repeats: true) { [weak self] _ in
            self?.pollPasteboard()
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func pollPasteboard() {
        let currentChangeCount = NSPasteboard.general.changeCount
        guard currentChangeCount != lastChangeCount else { return }

        // 1. Check if this change count was generated by Clippy itself
        Self.lock.lock()
        let isIgnored = Self.ignoredChangeCounts.remove(currentChangeCount) != nil
        Self.lock.unlock()

        if isIgnored {
            lastChangeCount = currentChangeCount
            return
        }

        // 2. Check if the pasteboard has Clippy's internal marker
        if NSPasteboard.general.types?.contains(.clippyInternalMarker) == true {
            lastChangeCount = currentChangeCount
            return
        }

        lastChangeCount = currentChangeCount

        // Captured immediately, before reading pasteboard content, so it
        // reflects whichever app was frontmost at the moment of the change.
        let sourceApp = AppInfoProvider.currentSource()

        // Check if the source app is in the excluded apps list
        if let bundleId = sourceApp?.bundleId, !bundleId.isEmpty, AppInfoProvider.excludedAppIDs.contains(bundleId) {
            return
        }

        guard let (item, payload) = ClipboardReader.readCurrent() else { return }

        handle(item: item, payload: payload, sourceApp: sourceApp)
    }

    private func handle(item rawItem: ClipboardItem, payload: ClipboardPayload, sourceApp: AppSource?) {
        // Classify (and flag sensitivity) before this item ever touches disk.
        let classification = ContentClassifier.classify(payload)
        let isSourcePasswordManager = SensitiveDataDetector.isPasswordManager(bundleId: sourceApp?.bundleId)
        let isSensitive = classification.isSensitive || isSourcePasswordManager

        // If sensitive content is configured to be blocked entirely, drop it immediately.
        if isSensitive && PrivacyPreferences.shared.blockSensitiveItems {
            return
        }

        var item = rawItem
        item.type = classification.type
        item.isSensitive = isSensitive
        item.sourceApp = sourceApp

        let shouldEncrypt = isSensitive && PrivacyPreferences.shared.alwaysEncryptSensitive
        item.isEncrypted = shouldEncrypt

        // Mask preview if encrypted or autoMaskSensitive so plaintext sensitive data is never saved to metadata.json
        if shouldEncrypt || (isSensitive && PrivacyPreferences.shared.autoMaskSensitive) {
            item.preview = "••••••••"
        }

        if isSensitive && PrivacyPreferences.shared.autoPurgeSensitive {
            item.scheduledPurgeAt = Date().addingTimeInterval(PrivacyPreferences.shared.autoPurgeInterval)
        }

        do {
            var items = try MetadataStore.load()

            // If an item with the same contentHash already exists anywhere in history,
            // refresh its lastUsedAt and update its sourceApp rather than creating a duplicate.
            if let existingIndex = items.firstIndex(where: { $0.contentHash == item.contentHash }) {
                items[existingIndex].lastUsedAt = item.createdAt
                if let sourceApp {
                    items[existingIndex].sourceApp = sourceApp
                }
                if isSensitive && PrivacyPreferences.shared.autoPurgeSensitive {
                    items[existingIndex].scheduledPurgeAt = Date().addingTimeInterval(PrivacyPreferences.shared.autoPurgeInterval)
                }
                try MetadataStore.save(items)
                let updated = items[existingIndex]
                onUpdateItem?(updated)
                DispatchQueue.main.async {
                    if PasteQueueManager.shared.isActive {
                        PasteQueueManager.shared.enqueue(updated)
                    }
                }
                return
            }

            // Persist content (encrypted at rest if sensitive)
            item.storagePath = try persist(payload: payload, for: item)
            if case .image(let data) = payload {
                if let (thumbImage, thumbData) = ImageCache.shared.downsample(data: data, maxDimension: 350) {
                    if let thumbURL = try? AssetStore.writeThumbnail(thumbData, for: item.id, format: .jpg) {
                        item.thumbnailPath = thumbURL.path
                        ImageCache.shared.store(thumbImage, for: item.id.uuidString)
                    }
                }
            }
            items.append(item)
            try MetadataStore.save(items)
            onNewItem?(item)
            let captured = item
            DispatchQueue.main.async {
                if PasteQueueManager.shared.isActive {
                    PasteQueueManager.shared.enqueue(captured)
                }
            }

            // Asynchronously extract OCR text from image using Vision framework
            if case .image(let data) = payload {
                let itemID = item.id
                Task.detached(priority: .userInitiated) { [weak self] in
                    if let extracted = await ImageTextExtractor.extractText(from: data) {
                        do {
                            var currentItems = try MetadataStore.load()
                            if let idx = currentItems.firstIndex(where: { $0.id == itemID }) {
                                currentItems[idx].extractedText = extracted
                                try MetadataStore.save(currentItems)
                                let updatedItem = currentItems[idx]
                                self?.onUpdateItem?(updatedItem)
                            }
                        } catch {
                            print("ClipboardMonitor: failed to save OCR text: \(error)")
                        }
                    }
                }
            }
        } catch {
            print("ClipboardMonitor: failed to persist clipboard item: \(error)")
        }
    }

    private func persist(payload: ClipboardPayload, for item: ClipboardItem) throws -> String {
        switch payload {
        case .text(let string):
            if item.isEncrypted {
                let data = try ContentEncryptor.encrypt(Data(string.utf8))
                return try AssetStore.writeEncryptedText(data, for: item.id).path
            } else {
                return try AssetStore.writeText(string, for: item.id).path
            }
        case .richText(let data):
            if item.isEncrypted {
                let encrypted = try ContentEncryptor.encrypt(data)
                return try AssetStore.writeEncryptedRichText(encrypted, for: item.id).path
            } else {
                return try AssetStore.writeRichText(data, for: item.id).path
            }
        case .image(let data):
            return try AssetStore.writeImage(data, for: item.id, format: .png).path
        case .fileURL(let url):
            return try AssetStore.writeFile(from: url, for: item.id).path
        }
    }
}